# Generated by Django 6.0 on 2026-05-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wearable_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearablesnapshot',
            name='provider',
            field=models.CharField(choices=[('samsung_health', 'Samsung Health'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.DeleteModel(
            name='WearableConnection',
        ),
    ]
